### ISSUE TITLE
[bug]貌似未auth会出错。

### ISSUE THREAD

**Issue by jinleileiking** [ireaderlab/zkdash#22]
```
D 170109 13:38:47 connection:282] Sending request(xid=1173): GetChildren(path=u'/elastic-job-example-lite-spring/springSimpleJob/servers/10.65.128.186/trigger', watcher=None)
[D 170109 13:38:47 connection:352] Received error(xid=1173) NoAuthError((), {})
[E 170109 13:38:47 base:132] Internal Error: Traceback (most recent call last):
      File "/home/jinlei1/tools/zkdash/handler/bases/base.py", line 128, in _exec
        res = self.response()
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2601, in wrapper
        return method(self, *args, **kwargs)
      File "/home/jinlei1/tools/zkdash/handler/config/znode.py", line 77, in response
        ZnodeService.get_znode_tree(zoo_client, normalized_path, nodes)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 146, in get_znode_tree
        get_znode_tree(zoo_client, child_path, nodes, child_id, current_id)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 146, in get_znode_tree
        get_znode_tree(zoo_client, child_path, nodes, child_id, current_id)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 146, in get_znode_tree
        get_znode_tree(zoo_client, child_path, nodes, child_id, current_id)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 146, in get_znode_tree
        get_znode_tree(zoo_client, child_path, nodes, child_id, current_id)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 146, in get_znode_tree
        get_znode_tree(zoo_client, child_path, nodes, child_id, current_id)
      File "/home/jinlei1/tools/zkdash/service/znode.py", line 136, in get_znode_tree
        children = zoo_client.get_children(path)
      File "/usr/local/lib/python2.7/site-packages/kazoo/client.py", line 1078, in get_children
        return self.get_children_async(path, watch, include_data).get()
      File "/usr/local/lib/python2.7/site-packages/kazoo/handlers/utils.py", line 78, in get
        raise self._exception
    NoAuthError: ((), {})
```

**Comment by xidianwlc** [comment]
目前不支持zk auth机制
