### ISSUE TITLE
'MyRetryDB' object has no attribute 'field_overrides'

### ISSUE THREAD

**Issue by danneycao** [ireaderlab/zkdash#28]
[root@localhost bin]# python syncdb.py
Traceback (most recent call last):
  File "syncdb.py", line 19, in <module>
    from model.db.base import ZKDASH_DB
  File "/home/danneycao/open_src/zkdash/model/db/base.py", line 18, in <module>
    ZKDASH_DB = Database(**DATABASE)
  File "/home/danneycao/open_src/zkdash/lib/db/database.py", line 26, in __init__
    self.load_database()
  File "/home/danneycao/open_src/zkdash/lib/db/database.py", line 32, in load_database
    self.database.field_overrides.update({'enum': 'enum'})  # 增加枚举类型
AttributeError: 'MyRetryDB' object has no attribute 'field_overrides'

**Comment by xidianwlc** [comment]
应该是安装的peewee版本不匹配的问题，建议参考peewee文档
