### ISSUE TITLE
启动报错：初始化数据库

### ISSUE THREAD

**Issue by kevinjiang2022** [ireaderlab/zkdash#33]
python ./bin/syncdb.py 
Traceback (most recent call last):
  File "./bin/syncdb.py", line 19, in <module>
    from model.db.base import ZKDASH_DB
  File "/Users/peirong.jiang/PycharmProjects/zkdash/model/db/base.py", line 12, in <module>
    from peewee import Field
ImportError: No module named peewee

**Comment by kevinjiang2022** [comment]
找到原因了，不能使用py3.x以上的版本，只能用2.7
