### ISSUE TITLE
新安装zkdash，出现import问题

### ISSUE THREAD

**Issue by onezero11010** [ireaderlab/zkdash#8]
Traceback (most recent call last):
  File "init.py", line 86, in <module>
    main()
  File "init.py", line 78, in main
    application = Application()
  File "init.py", line 35, in **init**
    routes = load('handler')
  File "/root/zkdash/lib/utils/routes.py", line 109, in load
    **import**(modname)
  File "/root/zkdash/handler/config/znode.py", line 27, in <module>
    from service import znode as ZnodeService
  File "/root/zkdash/service/znode.py", line 16, in <module>
    from lib.zyqconf import qconf_py
  File "/root/zkdash/lib/zyqconf/**init**.py", line 12, in <module>
    import qconf_py
qconf_py.Error: inital qconf evn failed!

**Comment by paderma** [comment]
这是因为在加载qconf_py模块时环境依赖问题导致的异常，已经修复这个问题，拉取最新代码即可

**Comment by onezero11010** [comment]
thanks
